;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Character.Teleported",DevComment="")
GameplayTagList=(Tag="Event.Combo.End",DevComment="")
GameplayTagList=(Tag="Event.Combo.Input",DevComment="")
GameplayTagList=(Tag="Event.Combo.Start",DevComment="")
GameplayTagList=(Tag="Event.Hitscan.End",DevComment="")
GameplayTagList=(Tag="Event.Hitscan.End.FullBody",DevComment="")
GameplayTagList=(Tag="Event.Hitscan.End.LeftHand",DevComment="")
GameplayTagList=(Tag="Event.Hitscan.End.RightHand",DevComment="")
GameplayTagList=(Tag="Event.Hitscan.Start",DevComment="")
GameplayTagList=(Tag="Event.Hitscan.Start.Fullbody",DevComment="")
GameplayTagList=(Tag="Event.Hitscan.Start.LeftHand",DevComment="")
GameplayTagList=(Tag="Event.Hitscan.Start.RightHand",DevComment="")
GameplayTagList=(Tag="Event.Montage.Trigger",DevComment="")
GameplayTagList=(Tag="Event.Projectile.Shoot",DevComment="")
GameplayTagList=(Tag="GameplayCue.AOE.Indicator",DevComment="")
GameplayTagList=(Tag="GameplayCue.AOE.Lightning",DevComment="")
GameplayTagList=(Tag="GameplayCue.Damage",DevComment="")
GameplayTagList=(Tag="GameplayCue.Dash",DevComment="")
GameplayTagList=(Tag="GameplayCue.Projectile.Hit.Nature",DevComment="")
GameplayTagList=(Tag="GameplayCue.Projectile.Spawn.Nature",DevComment="")
GameplayTagList=(Tag="GameplayCue.Shield.Effect",DevComment="")
GameplayTagList=(Tag="Gas.Ability.Active",DevComment="")
GameplayTagList=(Tag="Gas.Ability.Aoe",DevComment="")
GameplayTagList=(Tag="Gas.Ability.Aoe.Finish",DevComment="")
GameplayTagList=(Tag="Gas.Ability.Attack.Melee",DevComment="")
GameplayTagList=(Tag="Gas.Ability.Attack.Shoot",DevComment="")
GameplayTagList=(Tag="Gas.Ability.Defense.Shield",DevComment="")
GameplayTagList=(Tag="Gas.Ability.Movement.Dash",DevComment="")
GameplayTagList=(Tag="Gas.Ability.Movement.FlyDash",DevComment="")
GameplayTagList=(Tag="Gas.Ability.Movement.RollDash",DevComment="")
GameplayTagList=(Tag="Gas.Ability.RollDash",DevComment="")
GameplayTagList=(Tag="Gas.BlockRegen.Stamina",DevComment="")
GameplayTagList=(Tag="Gas.Cooldown.AOE",DevComment="")
GameplayTagList=(Tag="Gas.Cooldown.Dash",DevComment="")
GameplayTagList=(Tag="Gas.Cooldown.Duration",DevComment="")
GameplayTagList=(Tag="Gas.Cooldown.Flying",DevComment="")
GameplayTagList=(Tag="Gas.Cooldown.Shield",DevComment="")
GameplayTagList=(Tag="Gas.Cost.Mana",DevComment="")
GameplayTagList=(Tag="Gas.Cost.Stamina",DevComment="")
GameplayTagList=(Tag="Gas.Data",DevComment="")
GameplayTagList=(Tag="Gas.Data.Damage",DevComment="")
GameplayTagList=(Tag="Gas.Flying",DevComment="")
GameplayTagList=(Tag="Gas.Frozen",DevComment="")
GameplayTagList=(Tag="Gas.Hit.Hitreaction",DevComment="")
GameplayTagList=(Tag="Gas.Immobilie",DevComment="")
GameplayTagList=(Tag="Gas.Init.Max",DevComment="")
GameplayTagList=(Tag="Gas.Interact.Hurt",DevComment="")
GameplayTagList=(Tag="Gas.Interact.Hurt.Fullbody",DevComment="")
GameplayTagList=(Tag="Gas.Regen.Health",DevComment="")
GameplayTagList=(Tag="Gas.Regen.Mana",DevComment="")
GameplayTagList=(Tag="Gas.Regen.Shield",DevComment="")
GameplayTagList=(Tag="Gas.Regen.Stamina",DevComment="")
GameplayTagList=(Tag="Gas.Shield.Effect",DevComment="")
GameplayTagList=(Tag="Gas.Stamina.Cost",DevComment="")
GameplayTagList=(Tag="Gas.Status.Buff.Shield",DevComment="")
GameplayTagList=(Tag="Gas.Status.Dead",DevComment="")
GameplayTagList=(Tag="Gas.Status.Debuff.Frozen",DevComment="")
GameplayTagList=(Tag="Gas.Status.Hit",DevComment="")

